"""fix set-card relationships and cascade

Revision ID: 229310e4a3be
Revises: ba75bdf7219f
Create Date: 2026-03-04 20:28:37.801203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229310e4a3be'
down_revision = 'ba75bdf7219f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cards", schema=None, recreate="always") as batch_op:
        # FK wird beim Recreate automatisch neu erstellt
        batch_op.create_foreign_key(
            "fk_cards_set_id_sets",
            "sets",
            ["set_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cards", schema=None, recreate="always") as batch_op:
        batch_op.drop_constraint("fk_cards_set_id_sets", type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_cards_set_id_sets",
            "sets",
            ["set_id"],
            ["id"],
        )

    # ### end Alembic commands ###
